// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbydnQWGj6-3zcNSVfAeKAKln1qL9W3RY',
    appId: '1:1064362251257:web:0a9375e0db33c0c3dde328',
    messagingSenderId: '1064362251257',
    projectId: 'finalproject-4a4e4',
    authDomain: 'finalproject-4a4e4.firebaseapp.com',
    storageBucket: 'finalproject-4a4e4.appspot.com',
    measurementId: 'G-5P8J693GYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNcq-OniVVWk2BSvzvE4gENGOoyvmBNlY',
    appId: '1:1064362251257:android:b5b5ed815597d3a6dde328',
    messagingSenderId: '1064362251257',
    projectId: 'finalproject-4a4e4',
    storageBucket: 'finalproject-4a4e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuBPY0-P29nfRNdLZCiDbLAsDGc3wfn7w',
    appId: '1:1064362251257:ios:08d594ddab0eabf9dde328',
    messagingSenderId: '1064362251257',
    projectId: 'finalproject-4a4e4',
    storageBucket: 'finalproject-4a4e4.appspot.com',
    iosBundleId: 'com.example.jittirat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuBPY0-P29nfRNdLZCiDbLAsDGc3wfn7w',
    appId: '1:1064362251257:ios:08d594ddab0eabf9dde328',
    messagingSenderId: '1064362251257',
    projectId: 'finalproject-4a4e4',
    storageBucket: 'finalproject-4a4e4.appspot.com',
    iosBundleId: 'com.example.jittirat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbydnQWGj6-3zcNSVfAeKAKln1qL9W3RY',
    appId: '1:1064362251257:web:aeb7f2ef35f3572fdde328',
    messagingSenderId: '1064362251257',
    projectId: 'finalproject-4a4e4',
    authDomain: 'finalproject-4a4e4.firebaseapp.com',
    storageBucket: 'finalproject-4a4e4.appspot.com',
    measurementId: 'G-H94CG9M8HL',
  );

}